# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e7dd8670c0699f65b812009a93db2a4a70b0a64d906cdf26e9168ebe5d104a2abc1afd030879a691669eb8dd991f69b414388794a638e4521194de8f7d064dc

test:
  secret_key_base: b41ed8bffd146d806f150a09b6ecf713fd1fea78fcef4f20c9eb61377d2af73bf15bd88de452bfaf96f46e402af61668aca6fa080a695d7dff72c19fa4ed48a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
